notifications:
  email: false

language: python

python:
 - "3.6"

jobs:
  include:

    # Docker image
    - services:
      - docker
      os: linux
      dist: trusty
      sudo: required
      env: CONTAINER_TYPE=docker
      script:
        # Docker build
        - docker build -t "iosonofabio/organic-box-factory:$TRAVIS_BRANCH" .
        # Docker tests
        - docker run -v $(pwd)/example_data:/data/example_data -v $(pwd)/tests:/tests --name expressionmatrix2 --rm "iosonofabio/organic-box-factory:$TRAVIS_BRANCH" /bin/sh -c /tests/test.sh
        # Push to docker hub
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        - docker push "iosonofabio/organic-box-factory:$TRAVIS_BRANCH";

    # Singularity image
    - os: linux
      dist: trusty
      sudo: required
      env: CONTAINER_TYPE=singularity
      script:
        # Install singularity on the host
        - ./.travis_install_singularity.sh
        # Singularity build (from Singularity file)
        - sudo singularity create --size 2500 ./singularity_images/expressionmatrix2-singularity-bootstrap.img; sudo singularity bootstrap ./singularity_images/expressionmatrix2-singularity-bootstrap.img Singularity
        # Singularity tests
        - singularity exec singularity_images/expressionmatrix2-singularity-bootstrap.img tests/test.sh
        # Push to singularity hub
        # FIXME: can this be done programmatically at all??
